### ISSUE TITLE
Road to general usability

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#151]
Graphcool has since change to Prisma and then again to subsequent version. I need to remove it, for now, to work on getting this project stable. 

- [x] Swap out Graphcool repo list with GitHub forks or stars related #32 
- [x] [simplify new repo form to either clone or fork a repo](https://github.com/bdougie/open-sauced/issues/117)  
- [x] explore if mirroring repository and issues is a valuable way to store data, similar to how https://www.onegraph.com/changelog works related #117

**Comment by bdougie** [comment]
Final work will be UI + Design Systems and Note rendering error to close this out
#210 
#208

**Comment by bdougie** [comment]
I am now using this project for my contributions
